import { describe, expect, it } from 'vitest';
import { AnalyzerRegistry, createDefaultAnalyzerRegistry } from '../../../src/knowledge/analyzers/index.js';
import {
  ANALYZER_COVERAGE_DIAGNOSTIC_CODES,
  MAX_COVERAGE_DIAGNOSTICS,
  MAX_COVERAGE_MESSAGE_LENGTH,
  boundCoverageDiagnostics,
  classifyUnsupportedSource,
  coverageFromOptionalIngest,
  detectGeneratedCode,
  unsupportedCoverage,
} from '../../../src/knowledge/analyzers/AnalyzerCoverage.js';

describe('AnalyzerRegistry.resolve', () => {
  it('returns a supported resolution with analyzer identity and coverage', () => {
    const resolution = createDefaultAnalyzerRegistry().resolve({ sourcePath: 'src/app.py', mimeType: 'text/x-python' });

    expect(resolution.kind).toBe('supported');
    if (resolution.kind !== 'supported') return;
    expect(resolution.analyzer.id).toBe('python-lezer');
    expect(resolution.coverage).toMatchObject({
      status: 'supported',
      analyzerId: 'python-lezer',
      analyzerVersion: resolution.analyzer.version,
      generatedCode: false,
      generatedReason: null,
      missingFeatures: [],
      warnings: [],
    });
  });

  it('returns an unsupported resolution instead of throwing and is deterministic', () => {
    const registry = createDefaultAnalyzerRegistry();
    const input = { sourcePath: 'scripts/example.rb', mimeType: 'application/x-ruby' };

    const first = registry.resolve(input);
    expect(first.kind).toBe('unsupported');
    expect(first.coverage).toMatchObject({
      status: 'unsupported',
      analyzerId: null,
      analyzerVersion: null,
      unsupportedReason: 'no_analyzer',
    });
    expect(first.coverage.warnings).toEqual([
      expect.objectContaining({ code: 'coverage_no_analyzer', severity: 'warning' }),
    ]);
    expect(registry.resolve(input)).toEqual(first);
  });

  it('keeps require() as a legacy path that throws only for unsupported inputs', () => {
    const registry = new AnalyzerRegistry();
    expect(() => registry.require({ sourcePath: 'a.rb', mimeType: 'application/x-ruby' })).toThrow(/no deterministic analyzer/i);
  });

  it('marks generated paths as advisory without blocking support', () => {
    const resolution = createDefaultAnalyzerRegistry().resolve({ sourcePath: 'dist/app.min.js', mimeType: 'text/javascript' });
    expect(resolution.kind).toBe('supported');
    expect(resolution.coverage).toMatchObject({ status: 'supported', generatedCode: true, generatedReason: 'build_output' });
  });
});

describe('classifyUnsupportedSource', () => {
  it.each([
    [{ sourcePath: 'a.rb', mimeType: 'application/x-ruby' }, 'no_analyzer'],
    [{ sourcePath: 'LICENSE', mimeType: null }, 'unknown_format'],
    [{ sourcePath: null, mimeType: null }, 'unknown_format'],
    [{ sourcePath: 'blob.bin', mimeType: 'application/octet-stream' }, 'binary_or_non_text'],
    [{ sourcePath: 'a.zip', mimeType: 'application/zip' }, 'binary_or_non_text'],
    [{ sourcePath: 'report.pdf', mimeType: 'application/pdf' }, 'adapter_missing'],
    [{ sourcePath: 'photo.png', mimeType: 'image/png' }, 'adapter_missing'],
    [{ sourcePath: 'deck.pptx', mimeType: null }, 'adapter_missing'],
  ] as const)('classifies %j as %s', (input, reason) => {
    expect(classifyUnsupportedSource(input)).toBe(reason);
  });
});

describe('detectGeneratedCode', () => {
  it.each([
    [{ sourcePath: 'package-lock.json' }, 'lockfile'],
    [{ sourcePath: 'pnpm-lock.yaml' }, 'lockfile'],
    [{ sourcePath: 'web/dist/bundle.js' }, 'build_output'],
    [{ sourcePath: 'api/service_pb2.py' }, 'generated_path'],
    [{ sourcePath: 'src/x.ts', content: '// @generated by tool\nexport const a = 1;\n' }, 'generated_marker'],
    [{ sourcePath: 'src/y.py', content: '# Code generated by protoc. DO NOT EDIT.\n' }, 'generated_marker'],
  ] as const)('detects %j as %s', (input, reason) => {
    expect(detectGeneratedCode(input)).toEqual({ generated: true, reason });
  });

  it('does not flag ordinary sources or markers past the header window', () => {
    expect(detectGeneratedCode({ sourcePath: 'src/app.ts', content: 'export const a = 1;\n' })).toEqual({
      generated: false,
      reason: null,
    });
    expect(
      detectGeneratedCode({ sourcePath: 'src/app.ts', content: `${'x\n'.repeat(4000)}// @generated\n` }).generated,
    ).toBe(false);
  });
});

describe('optional ingest outcomes', () => {
  it('maps document and media ingest outcomes to unified coverage', () => {
    const input = { sourcePath: 'report.pdf', mimeType: 'application/pdf' };
    expect(coverageFromOptionalIngest({ status: 'unsupported', reason: 'no_adapter' }, input)).toMatchObject({
      status: 'unsupported',
      unsupportedReason: 'adapter_missing',
      warnings: [expect.objectContaining({ code: 'coverage_adapter_missing' })],
    });
    expect(coverageFromOptionalIngest({ status: 'unsupported', reason: 'unknown_format' }, input)).toMatchObject({
      status: 'unsupported',
      unsupportedReason: 'unknown_format',
      warnings: [expect.objectContaining({ code: 'coverage_unknown_format' })],
    });
    expect(coverageFromOptionalIngest({ status: 'failed', code: 'size_limit_exceeded' }, input)).toMatchObject({
      status: 'unsupported',
      unsupportedReason: 'size_limit_exceeded',
      warnings: [expect.objectContaining({ code: 'coverage_size_limit_exceeded' })],
    });
    expect(coverageFromOptionalIngest({ status: 'failed', code: 'parser_failed' }, input)).toMatchObject({
      status: 'failed',
      unsupportedReason: 'parser_failed',
      warnings: [expect.objectContaining({ code: 'coverage_parser_failed', severity: 'error' })],
    });
  });

  it('never carries raw error text from a failed ingest', () => {
    const coverage = coverageFromOptionalIngest(
      { status: 'failed', code: 'parser_failed', error: 'secret token=abc123 at /home/user/x' } as never,
      { sourcePath: 'a.pdf', mimeType: 'application/pdf' },
    );
    expect(JSON.stringify(coverage)).not.toContain('abc123');
    expect(JSON.stringify(coverage)).not.toContain('/home/user');
  });
});

describe('unsupportedCoverage and diagnostics bounds', () => {
  it('uses only stable diagnostic codes, mime and extension, never the full path', () => {
    const coverage = unsupportedCoverage('no_analyzer', { sourcePath: '/home/private/project/secret/a.rb', mimeType: 'application/x-ruby' });
    const [diagnostic] = coverage.warnings;
    expect(ANALYZER_COVERAGE_DIAGNOSTIC_CODES).toContain(diagnostic!.code);
    expect(diagnostic!.message).toContain('.rb');
    expect(diagnostic!.message).toContain('application/x-ruby');
    expect(diagnostic!.message).not.toContain('/home/private');
  });

  it('bounds, redacts, and deduplicates diagnostics', () => {
    const many = Array.from({ length: 30 }, (_, index) => ({
      code: `coverage_partial_dynamic_relationships`,
      message: `${index} ${'y'.repeat(1000)} token=sk-abcdefghijklmnopqrstuvwxyz0123456789`,
      severity: 'warning' as const,
      span: { startOffset: 0, endOffset: 1, startLine: 1, startColumn: 1, endLine: 1, endColumn: 2 },
    }));
    const bounded = boundCoverageDiagnostics([...many, ...many]);
    expect(bounded).toHaveLength(MAX_COVERAGE_DIAGNOSTICS);
    for (const diagnostic of bounded) {
      expect(diagnostic.message.length).toBeLessThanOrEqual(MAX_COVERAGE_MESSAGE_LENGTH);
      expect(diagnostic.message).not.toContain('sk-abcdefghijklmnopqrstuvwxyz0123456789');
      expect(diagnostic).not.toHaveProperty('span');
    }
  });
});
